# Generated by Django 4.1.13 on 2026-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(max_length=20)),
                ("date_naissance", models.DateField()),
                ("adresse", models.TextField()),
            ],
        ),
    ]
