# Generated by Django 6.0.4 on 2026-04-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="antecedents",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="groupe_sanguin",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="sexe",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                null=True,
            ),
        ),
    ]
