# Generated by Django 4.1.13 on 2026-04-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_rendezvous", models.DateTimeField()),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("planifie", "Planifié"),
                            ("termine", "Terminé"),
                            ("annule", "Annulé"),
                        ],
                        default="planifie",
                        max_length=20,
                    ),
                ),
                ("diagnostic", models.TextField(blank=True, null=True)),
                ("observation", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
