# Generated by Django 6.0.4 on 2026-04-19 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0002_initial"),
        ("patients", "0003_patient_antecedents_patient_groupe_sanguin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="consultation",
            options={"ordering": ["-date_rendezvous"]},
        ),
        migrations.AddField(
            model_name="consultation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="consultation",
            name="ordonnance",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="medecin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultations",
                to="patients.patient",
            ),
        ),
    ]
