# Generated by Django 6.0.4 on 2026-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0003_alter_consultation_options_consultation_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="consultation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="statut",
            field=models.CharField(
                choices=[
                    ("planifie", "Planifié"),
                    ("en_cours", "En cours"),
                    ("termine", "Terminé"),
                    ("annule", "Annulé"),
                ],
                default="planifie",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="consultation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
