# Generated by Django 6.0.4 on 2026-04-19 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultations",
            "0003_alter_consultation_options_consultation_created_at_and_more",
        ),
        ("paiements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paiement",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paiement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("paye", "Payé"),
                    ("en_attente", "En attente"),
                    ("rembourse", "Remboursé"),
                ],
                default="en_attente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="consultation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="consultations.consultation",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="methode",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("carte", "Carte bancaire"),
                    ("virement", "Virement"),
                    ("assurance", "Assurance"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="montant",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
