# Generated by Django 6.0.4 on 2026-04-19 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0004_alter_consultation_created_at_and_more"),
        ("paiements", "0002_paiement_notes_paiement_statut_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paiement",
            name="consultation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="paiement",
                to="consultations.consultation",
            ),
        ),
        migrations.AlterField(
            model_name="paiement",
            name="methode",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("carte", "Carte bancaire"),
                    ("virement", "Virement"),
                    ("assurance", "Assurance"),
                ],
                default="cash",
                max_length=50,
            ),
        ),
    ]
