# Generated by Django 6.0.4 on 2026-04-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_photo_user_telephone_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("medecin", "Médecin"),
                    ("secretaire", "Secrétaire"),
                    ("patient", "Patient"),
                ],
                default="patient",
                max_length=20,
            ),
        ),
    ]
