# Generated by Django 6.0.4 on 2026-04-19 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Medecin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialite",
                    models.CharField(
                        choices=[
                            ("generaliste", "Médecin Généraliste"),
                            ("cardiologue", "Cardiologue"),
                            ("dermatologue", "Dermatologue"),
                            ("pediatre", "Pédiatre"),
                            ("autre", "Autre"),
                        ],
                        default="generaliste",
                        max_length=100,
                    ),
                ),
                (
                    "numero_ordre",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("disponible", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medecin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
